### ISSUE TITLE
Can you provide the two references?

### ISSUE THREAD

**Issue by 461353349** [s-weisser/surface-segmentation#1]
References
S. Rjasanow, O. Steinbach: The fast solution of boundary integral equations. Math. Anal. Tech. Appl. Eng., Springer, New York, 2007
S. Rjasanow, S. Weißer: ACA improvement by surface segmentation, 2018 (submitted)

**Comment by s-weisser** [comment]
Due to copyright reasons I cannot provide the first reference, which is a Springer book.

The second reference can be shared in a personal mail for academic use. It will be published as:

S. Rjasanow and S. Weißer, ACA improvement by surface segmentation. In: T. Apel, O. Steinbach (Eds.), _Advanced Finite Element Methods with Applications - Proceedings of the 30th Chemnitz FEM Symposium 2017_, Lecture Notes in Computational Science and Engineering (LNCSE), Springer International Publishing, 2019
